packages:
  - apps/*
  - packages/*
allowBuilds:
  '@swc/core': true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.64'
  - '@hono/node-server@2.1.1'
  - ai@7.0.79
  - hono@4.13.5
