import type { ArtifactRecord } from "@/model/artifact";
import type {
  ResourceChunk,
  ResourceLocator,
  ResourceRecord,
} from "@/model/resource";
import type {
  StageArtifact,
  StageArtifactSource,
  StageArtifactStatus,
  StageDocumentPage,
  StageVideoTranscriptCue,
} from "@/model/stage-workspace";
import { resourceRepository } from "./indexed-db-v2";
import type { ResourceRepository } from "./repository";
import {
  createStageDocumentPreviewSource,
  registerStageDocumentPreviewSource,
} from "./stage-document-preview";

const STATIC_RASTER_MIME_TYPES = new Set([
  "image/avif",
  "image/jpeg",
  "image/png",
  "image/webp",
]);

export type StageArtifactResourceRepository = Pick<
  ResourceRepository,
  "getArtifact" | "getResource" | "getResourceBlob" | "getResourceChunks"
>;

export interface StageObjectUrlAdapter {
  create(blob: Blob): string;
  revoke(url: string): void;
}

export interface StageArtifactLoaderOptions {
  repository?: StageArtifactResourceRepository;
  objectUrls?: StageObjectUrlAdapter;
}

export interface LoadedStageArtifact {
  artifact: StageArtifact;
  /** Idempotently releases object URLs owned by this loaded view. */
  dispose(): void;
}

function defaultObjectUrls(): StageObjectUrlAdapter {
  return {
    create(blob) {
      if (typeof URL === "undefined" || typeof URL.createObjectURL !== "function") {
        throw new Error("This browser cannot create a local resource preview URL.");
      }
      return URL.createObjectURL(blob);
    },
    revoke(url) {
      URL.revokeObjectURL(url);
    },
  };
}

function stageStatus(resource: ResourceRecord): StageArtifactStatus {
  switch (resource.status) {
    case "pending":
      return "queued";
    case "processing":
      return "loading";
    case "ready":
      return "ready";
    case "error":
      return "error";
  }
}

function sourceFor(artifact: ArtifactRecord, resource: ResourceRecord): StageArtifactSource {
  const url = artifact.sourceUrl ?? resource.sourceUrl;
  let label = resource.name;
  if (url) {
    try {
      label = new URL(url).hostname || resource.name;
    } catch {
      label = resource.name;
    }
  } else if (resource.origin === "generated") {
    label = "Generated by AI";
  }
  return {
    label,
    detail: resource.name,
    ...(url ? { url } : {}),
  };
}

function locatorMatches(chunk: ResourceChunk, target: ResourceLocator | undefined): boolean {
  if (!target) return true;
  const locator = chunk.locator;
  if (target.page !== undefined && locator.page !== target.page) return false;
  if (target.slide !== undefined && locator.slide !== target.slide) return false;
  if (target.label !== undefined && locator.label !== target.label) return false;
  if (target.startSeconds !== undefined && (locator.endSeconds ?? 0) <= target.startSeconds) return false;
  if (target.endSeconds !== undefined && (locator.startSeconds ?? Number.MAX_SAFE_INTEGER) >= target.endSeconds) {
    return false;
  }
  if (target.startChar !== undefined && (locator.endChar ?? 0) <= target.startChar) return false;
  if (target.endChar !== undefined && (locator.startChar ?? Number.MAX_SAFE_INTEGER) >= target.endChar) return false;
  return true;
}

function textWithinLocator(chunk: ResourceChunk, target: ResourceLocator | undefined): string {
  if (!target) return chunk.text;
  const chunkStart = chunk.locator.startChar ?? 0;
  const from = target.startChar === undefined ? 0 : Math.max(target.startChar - chunkStart, 0);
  const to = target.endChar === undefined
    ? chunk.text.length
    : Math.min(Math.max(target.endChar - chunkStart, 0), chunk.text.length);
  return chunk.text.slice(Math.min(from, to), to);
}

function selectedChunks(chunks: readonly ResourceChunk[], locator: ResourceLocator | undefined): ResourceChunk[] {
  return chunks
    .filter((chunk) => locatorMatches(chunk, locator))
    .map((chunk) => ({ ...chunk, text: textWithinLocator(chunk, locator) }))
    .filter((chunk) => chunk.text.length > 0)
    .sort((left, right) => left.index - right.index);
}

function joinedText(chunks: readonly ResourceChunk[]): string {
  return chunks.map((chunk) => chunk.text).join("");
}

function numberedPages(
  resource: ResourceRecord,
  chunks: readonly ResourceChunk[],
  locator: ResourceLocator | undefined,
): StageDocumentPage[] {
  const locatorKey = resource.kind === "pptx" ? "slide" : "page";
  const selectedNumber = locator?.[locatorKey];
  const declaredCount = resource.kind === "pptx"
    ? resource.metadata.slideCount
    : resource.kind === "pdf"
      ? resource.metadata.pageCount
      : undefined;
  const discoveredNumbers = [...new Set(chunks.flatMap((chunk) => {
    const value = chunk.locator[locatorKey];
    return value === undefined ? [] : [value];
  }))].sort((left, right) => left - right);
  const numbers = selectedNumber !== undefined
    ? [selectedNumber]
    : declaredCount !== undefined
      ? Array.from({ length: declaredCount }, (_, index) => index + 1)
      : discoveredNumbers.length > 0
        ? discoveredNumbers
        : [1];
  return numbers.map((number) => {
    const matching = chunks.filter((chunk) => chunk.locator[locatorKey] === number);
    const fallbackLabel = resource.kind === "pptx" ? `Slide ${number}` : `Page ${number}`;
    return {
      id: `${resource.id}:${locatorKey}:${number}`,
      label: matching[0]?.locator.label ?? fallbackLabel,
      sourcePageIndex: number - 1,
      text: joinedText(matching),
    };
  });
}

function documentPages(
  resource: ResourceRecord,
  chunks: readonly ResourceChunk[],
  locator: ResourceLocator | undefined,
): StageDocumentPage[] {
  if (resource.kind === "pdf" || resource.kind === "pptx") {
    return numberedPages(resource, chunks, locator);
  }
  if (resource.kind === "docx" && resource.metadata.pageCount !== undefined) {
    const selectedPage = locator?.page;
    const pageNumbers = selectedPage === undefined
      ? Array.from({ length: resource.metadata.pageCount }, (_, index) => index + 1)
      : [selectedPage];
    return pageNumbers.map((pageNumber, index) => ({
      id: `${resource.id}:page:${pageNumber}`,
      label: `Page ${pageNumber}`,
      sourcePageIndex: pageNumber - 1,
      ...(index === 0 ? { text: joinedText(chunks) } : {}),
    }));
  }
  return [{
    id: `${resource.id}:document`,
    label: locator?.label ?? "Document",
    sourcePageIndex: locator?.page === undefined ? 0 : locator.page - 1,
    text: joinedText(chunks),
  }];
}

function transcriptCues(chunks: readonly ResourceChunk[]): StageVideoTranscriptCue[] {
  return chunks.map((chunk) => ({
    id: chunk.id,
    startMs: Math.max(Math.round((chunk.locator.startSeconds ?? 0) * 1_000), 0),
    ...(chunk.locator.endSeconds === undefined
      ? {}
      : { endMs: Math.max(Math.round(chunk.locator.endSeconds * 1_000), 0) }),
    text: chunk.text,
    ...(chunk.locator.label ? { speaker: chunk.locator.label } : {}),
  }));
}

async function loadBlobUrl(
  repository: StageArtifactResourceRepository,
  resource: ResourceRecord,
  urls: StageObjectUrlAdapter,
  ownedUrls: string[],
): Promise<string | undefined> {
  const declaredMimeType = resource.mimeType.toLocaleLowerCase();
  if (resource.kind !== "image"
    || resource.status !== "ready"
    || !STATIC_RASTER_MIME_TYPES.has(declaredMimeType)) return undefined;
  const blobRecord = await repository.getResourceBlob(resource.id);
  if (!blobRecord) return undefined;
  const recordMimeType = blobRecord.mimeType.toLocaleLowerCase();
  const blobMimeType = blobRecord.blob.type.toLocaleLowerCase();
  if (!STATIC_RASTER_MIME_TYPES.has(recordMimeType)
    || (blobMimeType && !STATIC_RASTER_MIME_TYPES.has(blobMimeType))) return undefined;
  const url = urls.create(blobRecord.blob);
  ownedUrls.push(url);
  return url;
}

async function loadStaticPreviewUrl(
  artifact: ArtifactRecord,
  repository: StageArtifactResourceRepository,
  urls: StageObjectUrlAdapter,
  ownedUrls: string[],
): Promise<{ resource: ResourceRecord; url: string } | undefined> {
  if (!artifact.previewResourceId) return undefined;
  const preview = await repository.getResource(artifact.previewResourceId);
  if (!preview
    || preview.conversationId !== artifact.conversationId
    || preview.kind !== "image"
    || preview.status !== "ready"
    || !STATIC_RASTER_MIME_TYPES.has(preview.mimeType.toLocaleLowerCase())) {
    return undefined;
  }
  const url = await loadBlobUrl(repository, preview, urls, ownedUrls);
  return url ? { resource: preview, url } : undefined;
}

function stageArtifactBase(artifact: ArtifactRecord, resource: ResourceRecord) {
  return {
    id: artifact.id,
    title: artifact.title,
    status: stageStatus(resource),
    createdAt: artifact.createdAt,
    updatedAt: Math.max(artifact.updatedAt, resource.updatedAt),
    source: sourceFor(artifact, resource),
    ...(resource.metadata.progress ? { progress: resource.metadata.progress } : {}),
    ...(resource.status === "error" ? { errorMessage: resource.errorMessage } : {}),
  };
}

async function resolveArtifactRecord(
  value: string | ArtifactRecord,
  repository: StageArtifactResourceRepository,
): Promise<ArtifactRecord> {
  if (typeof value !== "string") return value;
  const artifact = await repository.getArtifact(value);
  if (!artifact) throw new Error(`Artifact '${value}' was not found.`);
  return artifact;
}

/**
 * Resolves persistent records into the inert view model consumed by
 * StageDesktop. The caller must dispose the result when replacing/closing it.
 */
export async function loadStageArtifact(
  value: string | ArtifactRecord,
  options: StageArtifactLoaderOptions = {},
): Promise<LoadedStageArtifact> {
  const repository = options.repository ?? resourceRepository;
  const objectUrls = options.objectUrls ?? defaultObjectUrls();
  const ownedUrls: string[] = [];
  const ownedDisposers: Array<() => void> = [];
  let disposed = false;
  const dispose = () => {
    if (disposed) return;
    disposed = true;
    for (const url of ownedUrls) objectUrls.revoke(url);
    ownedUrls.length = 0;
    for (const release of ownedDisposers.splice(0)) release();
  };

  try {
    const artifact = await resolveArtifactRecord(value, repository);
    const resource = await repository.getResource(artifact.resourceId);
    if (!resource || resource.conversationId !== artifact.conversationId) {
      throw new Error(`Artifact '${artifact.id}' references an unavailable resource.`);
    }
    const base = stageArtifactBase(artifact, resource);
    if (resource.status !== "ready") {
      return { artifact: { ...base, kind: resource.kind } as StageArtifact, dispose };
    }

    const isOriginalDocument = resource.kind === "pdf" || resource.kind === "docx" || resource.kind === "pptx";
    const [chunks, storedDocumentBlob] = await Promise.all([
      resource.chunkCount > 0
        ? repository.getResourceChunks(resource.id).then((items) => selectedChunks(items, artifact.locator))
        : Promise.resolve([]),
      isOriginalDocument ? repository.getResourceBlob(resource.id) : Promise.resolve(undefined),
    ]);
    let stageArtifact: StageArtifact;
    switch (resource.kind) {
      case "pdf":
      case "docx":
      case "pptx": {
        const previewSource = storedDocumentBlob
          ? createStageDocumentPreviewSource(resource, storedDocumentBlob)
          : undefined;
        if (previewSource) {
          ownedDisposers.push(registerStageDocumentPreviewSource(artifact.id, previewSource));
        }
        stageArtifact = {
          ...base,
          kind: resource.kind,
          content: {
            pages: documentPages(resource, chunks, artifact.locator),
            ...(previewSource ? { originalPreviewAvailable: true } : {}),
          },
        };
        break;
      }
      case "text":
        stageArtifact = {
          ...base,
          kind: "text",
          content: { text: joinedText(chunks) },
        };
        break;
      case "image": {
        const preview = await loadStaticPreviewUrl(artifact, repository, objectUrls, ownedUrls);
        const imageUrl = preview?.url ?? await loadBlobUrl(repository, resource, objectUrls, ownedUrls);
        stageArtifact = imageUrl ? {
          ...base,
          kind: "image",
          content: {
            imageUrl,
            alt: resource.metadata.description ?? artifact.title,
            ...(resource.metadata.description ? { caption: resource.metadata.description } : {}),
          },
        } : {
          ...base,
          kind: "image",
          status: "error",
          errorMessage: "The image preview is unavailable.",
        };
        break;
      }
      case "svg": {
        const preview = await loadStaticPreviewUrl(artifact, repository, objectUrls, ownedUrls);
        stageArtifact = preview ? {
          ...base,
          kind: "svg",
          updatedAt: Math.max(base.updatedAt, preview.resource.updatedAt),
          content: {
            rasterPreviewUrl: preview.url,
            alt: preview.resource.metadata.description ?? resource.metadata.description ?? artifact.title,
            ...((resource.metadata.description ?? preview.resource.metadata.description)
              ? { caption: resource.metadata.description ?? preview.resource.metadata.description }
              : {}),
          },
        } : {
          ...base,
          kind: "svg",
          status: "error",
          errorMessage: "A static drawing preview is unavailable.",
        };
        break;
      }
      case "web": {
        const preview = await loadStaticPreviewUrl(artifact, repository, objectUrls, ownedUrls);
        stageArtifact = {
          ...base,
          kind: "web",
          content: {
            siteName: sourceFor(artifact, resource).label,
            byline: resource.metadata.author,
            text: joinedText(chunks),
            ...(preview ? {
              previewImageUrl: preview.url,
              previewImageAlt: preview.resource.metadata.description ?? `${artifact.title} preview`,
            } : {}),
          },
        };
        break;
      }
      case "video-transcript": {
        const preview = await loadStaticPreviewUrl(artifact, repository, objectUrls, ownedUrls);
        stageArtifact = {
          ...base,
          kind: "video-transcript",
          content: {
            cues: transcriptCues(chunks),
            ...(resource.metadata.durationSeconds === undefined
              ? {}
              : { durationMs: Math.round(resource.metadata.durationSeconds * 1_000) }),
            ...(preview ? {
              posterUrl: preview.url,
              posterAlt: preview.resource.metadata.description ?? `${artifact.title} poster`,
            } : {}),
          },
        };
        break;
      }
    }
    return { artifact: stageArtifact, dispose };
  } catch (error) {
    dispose();
    throw error;
  }
}
